config/routes.rb
Blogger::Application.routes.draw do
  devise_for :users

  get "tags/index"

  get "tags/show"

  get "comments/create"

  resources :articles
  resources :comments
  resources :tags
  
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end
  
  root to: 'articles#index'
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  body               :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :image
  
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  
  has_attached_file :image
  
  validates :title, presence: true
  validates :body, presence: true
  
  def tag_list
    return self.tags.join(", ")
  end
  
  def tag_list=(tag_string)
    self.taggings.destroy_all
    
    tag_names = tag_string.split(",").collect { |tag| tag.strip.downcase }.uniq
    
    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by_name(tag_name)
      tagging = self.taggings.new
      tagging.tag_id = tag.id
    end
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id          :integer          not null, primary key
#  article_id  :integer
#  author_name :string(255)
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Comment < ActiveRecord::Base
  attr_accessible :author_name, :body
  
  belongs_to :article
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
  attr_accessible :name
  
  has_many :taggings
  has_many :articles, through: :taggings
  
  def to_s
    name
  end
end

app/models/tagging.rb
# == Schema Information
#
# Table name: taggings
#
#  id         :integer          not null, primary key
#  tag_id     :integer
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tagging < ActiveRecord::Base
  attr_accessible :article_id, :tag_id
  
  belongs_to :article
  belongs_to :tag
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    if @article.save
      redirect_to article_path(@article)
    else
      flash[:error]
      render 'new'
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:message] = "Article '#{@article.title}' Updated!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def destroy
    Article.find(params[:id]).destroy
    redirect_to articles_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    article_id = params[:comment].delete(:article_id)

    @comment = Comment.new(params[:comment])
    @comment.article_id = article_id

    @comment.save

    redirect_to article_path(article_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
  
  def destroy
    Tag.find(params[:id]).destroy
    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def tag_links(tags)
    links = tags.collect { |tag| link_to tag.name, tag_path(tag) }
    return links.join(", ").html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div class="comment">
  <h4>Comment by <%= comment.author_name %></h4>
  <p><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </p>
  
  <% if @article.image_file_name %>
    <p><%= image_tag @article.image.url %></p>
  <% end %>
  <p>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>
  
  <p>
    <%= f.submit "Create new Article" %>
  </p>
  
<% end %>

app/views/articles/edit.html.erb
<h1>Edit your Article</h1>

<%= render 'articles/form' %>

app/views/articles/index.html.erb
<% if user_signed_in? %>
  <p><%= link_to "Sign out", sign_out_path %> | <%= link_to "Create New Article", new_article_path %></p>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

<h1>All Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: "article_title", 
                  id: "article_#{article.id}" %>
          <% if current_user %>
            <%= link_to " : Delete", article_path(article), method: :delete,
                      confirm: "Are you really sure you want to delete this?" %>
            <%= link_to " : Edit", edit_article_path(article) %>
          <% end %>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render 'articles/form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>Tags: <%= tag_links(@article.tags) %></p>
<% if @article.image_file_name %>
  <p><%= image_tag @article.image.url %></p>
<% end %>
<p><%= @article.body %></p>
<h3>Comments: (<%= @article.comments.count %>)</h3>
<%= render partial: 'comment', collection: @article.comments %>

<h3>Post a Comment</h3>

<%= form_for(@comment) do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name, "Your Name" %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="flash"><%= flash[:message] %></p>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/tags/index.html.erb
<h1>The following is the list of tags within the system:</h1>

<ul>
  <% @tags.each do |tag| %>
    <li><%= link_to tag.name, tag_path(tag) %>,
        <%= link_to "Delete", tag_path(tag), method: :delete, confirm: "Are you Sure?"%></li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>